name: Build and Push Docker Image

on:
  workflow_dispatch:

  push:
    branches:
      - master # ou la branche de votre choix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.CR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin


    - name: Build and push Docker image
      run: |
        mv .env.online .env
        docker build -t ghcr.io/${{ github.repository }}:online .
        docker push ghcr.io/${{ github.repository }}:online

    - name: Build and push Docker image
      run: |
        mv .env.home .env
        docker build -t ghcr.io/${{ github.repository }}:home .
        docker push ghcr.io/${{ github.repository }}:home
